server {
    listen 80;
    server_name 43.205.216.241 ;

    root /usr/share/nginx/html/game;
    index user_data.html front_page.html game.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
