server {
    listen 80;
    server_name 43.205.216.241;

    root /usr/share/nginx/html;
    index game.html front_page.html user_data.html index.html;

    location / {
        try_files $uri $uri/ /game.html;
    }
}

